language: python
python:
  - "3.6"
cache: pip
script:
  - export CODACY_PROJECT_TOKEN=7125a320acd5419db1151aa6a5fd954a
  - coverage run -m unittest discover -s ./tests && coverage xml && python-codacy-coverage -r coverage.xml
  - codecov
